name: CI

on:
    push: ~

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'
                  coverage: none
                  ini-values: date.timezone=UTC
                  tools: symfony-cli,composer

            - run: symfony composer require codeception/codeception:5.*

            - run: symfony run vendor/bin/codecept run
